### ISSUE TITLE
Legion Centurion Stats and points (Moritat Consul)

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#1]
The Legion Consul Upgrade:
Sets move Characteristics to 16" -> Should stay as default move range.
Jumppacks are set to forbidden, -> should be viable upgrade for Moritat
Should be armed with 2x Bolt Pistols when hhaving Moritat Consul upgrade.
Defualt statline should be: 
![image](https://user-images.githubusercontent.com/36841422/152697587-397365d7-e1d4-4c43-8e4c-3a079f15c46c.png)
but is showing as:
![image](https://user-images.githubusercontent.com/36841422/152697626-b6fda9b4-092c-4c8f-a211-742cbccc1cc1.png)

**Comment by rahtolsGitHub** [comment]
pts, stats and equipment fixed.
