### ISSUE TITLE
Alpha legion Headhunters causing Roster Error

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#10]
Alpha Legion Headhunters causing roster error due to too many elites. Probably due to elite keyword flagging up. Possible problem with other elite infantry for other legions but not tested..

**Comment by rahtolsGitHub** [comment]
Tried it without error. Could you please specify the selections so that i can check

**Comment by Count-Chamberlain** [comment]
![image](https://user-images.githubusercontent.com/36841422/167096064-12840331-b09b-49ae-b14e-a9b319e76104.png)


Only 3 Fast attack choises int he roster, but they also flag in Battlescribe as Elite choices.

**Comment by DeanHall01** [comment]
The Elite tag is still checked in the 20 Alpha Legion v11 root selection entry for the Headhunter Kill Team which is causing the OP error.  Hope this helps.

**Comment by rahtolsGitHub** [comment]
Hi, thanks for all the input. I'll change asap. Please keep posting errors you find. Nevertheless, i don't know If changing your local files can interfere If an update is released. If this should happen you'd have to deleted your local files and override them with the new released ones

**Comment by DeanHall01** [comment]
Happy to help.

**Comment by rahtolsGitHub** [comment]
Fixed. Unit is taken as Fast choice (added as Primary keyword), but also has the ELITE keyword. BattleScribe therefore counts both as valid, therefore returning the error.
