### ISSUE TITLE
Legion Tactical Support Squad

### ISSUE THREAD

**Issue by DeanHall01** [rahtolsGitHub/Unofficial-30k-9th-edition#11]
Love that you have done this Battlescribe data, thanks for your hard work.  I've listed what I did to fix the bugs in my local files as I find them.  If you don't find it helpful, just let me know and I'll stick to just the bugs.
Catz file - standard units and equipment library v28
30l9e Legiones Astartes v2.15

Legion space marines do not have points assigned - added points to entry

Rotor cannon points incorrect - increased pts to 10
Volkite charger points incorrect - reduced pts to 5

Plasma gun points 10 lower than expected - due to plasma gun shared selection entry not having points cost as other special weapons, I removed decrement pts by 10 on mine but could just as easily made plasma gun 10 pts but I haven't had a chance to look at what else that would effect yet

Additional chainsword does not have points assigned - added increment points by 1 repeating same as weapon options
Points in potential selection left pane (not sure what this is actually called) shows -5 points - fixed by adding min and max entries to Legion Tactical Support Squad entry group (UID 3277-9e3a-96b0-2b40)

**Comment by rahtolsGitHub** [comment]
Fixed
