### ISSUE TITLE
Too many/not enough fealty

### ISSUE THREAD

**Issue by DeanHall01** [rahtolsGitHub/Unofficial-30k-9th-edition#12]
Found this when working on RG decapitation strike RoW.

Main game system (gstz) file v13

When adding a second detachment, max/min fealty error is triggered.  Min error in second detachment when no fealty selection is added.  Max error when fealty selection is added to second detachment.

I fixed error by removing the min/max entries from the root selection entry for fealty.

**Comment by rahtolsGitHub** [comment]
Fixed
