### ISSUE TITLE
Breacher squads - points value incorrect

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#13]
Points showing 183 for barebones squad. Should be 18 per model and +3 per boarding shield. Totalling 210points. I think boarding shields are only being added once.

**Comment by DeanHall01** [comment]
Looks like that is what's happening.

@rahtolsGitHub changing Boarding shield (Collective) pts to 3 fixes the issue.

**Comment by rahtolsGitHub** [comment]
Fixed
