### ISSUE TITLE
Heavy weapons points cost on vehicles incorrect 

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#14]
Should be 25 for vehicles, 20 points for infantry
(Multimeltas, lascannons)
20 points for vehicles, 15 for infantry
(Heavy bolters,Missile launcher (with frag & krak missiles))
15 points for vehicles, 10 for infantry
(Plasma cannon, heavy flamer)

**Comment by rahtolsGitHub** [comment]
Done
