### ISSUE TITLE
Moritat consul roster error

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#15]
Error flags on Roster. Requires two bolt pistols only. 
Shows Jumppacks as not allowed.
![Screenshot_2022-05-11-08-56-28-74_14914093de79514ef0a2e5abb22c6172](https://user-images.githubusercontent.com/36841422/167800140-9697064f-ead1-499b-bbbe-dd481aaa9c8f.jpg)

**Comment by rahtolsGitHub** [comment]
Ist this with a Moritat selected?

**Comment by rahtolsGitHub** [comment]
He can only Take 2 pistols

**Comment by rahtolsGitHub** [comment]
And ni jump pack

**Comment by Count-Chamberlain** [comment]
"May not take a combi-weapon, boarding shield, bolter, power fist, thunder hammer, lightning claw(s), chainfist, Bike, Jetbike or 
Terminator armour."
They are allowed jumppacks, and the bolt pistols can be change with his base centurion rules: "This model can replace its bolt pistol with an item from the Pistols or Melee Weapons lists."

**Comment by Count-Chamberlain** [comment]
They are allowed jump packs from the Centurion base rules: A Legion Centurion can take a jump pack (+1 Power Rating). If it does, its Move Characteristic is increased to 
12”, and it gains the Fly and Jump Pack keywords and Jump Pack Assault special rule.

**Comment by rahtolsGitHub** [comment]
Yeah, my bad. Fixed.
