### ISSUE TITLE
Primus Nullicator Consul

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#17]
-Psyker option costs 2pl, this should be 1pl.
-has access to the Vigil Pattern Storm shield, I don't think it's supposed to.
-the Cataphractii terminator armour is optional, it should be compulsory (perhaps might be easier to move it to a Terminator centurion only?) 
-Cataphractii upgrade should not be free (i think)

**Comment by rahtolsGitHub** [comment]
Fixed.
