### ISSUE TITLE
Legion Preator

### ISSUE THREAD

**Issue by Count-Chamberlain** [rahtolsGitHub/Unofficial-30k-9th-edition#28]
Has "Marshal of the Storm" i believe that should only be for Dark Angels Preators.

**Comment by rahtolsGitHub** [comment]
Cant reproduce the error, please specify

**Comment by Count-Chamberlain** [comment]
![image](https://user-images.githubusercontent.com/36841422/170435358-87fed9a4-db2c-47e9-b419-f47d28d462b3.png)
![image](https://user-images.githubusercontent.com/36841422/170435448-e5fb8d39-3c3b-46d4-8083-0d624bc61bea.png)
First image frorm an Iron Hhands Roster, second from a Sons of Horus Roster, both showing the same ability. THis is on the PC build.

**Comment by rahtolsGitHub** [comment]
Fixed.
