### ISSUE TITLE
Legion Sicaran Weapon Upgrade problems

### ISSUE THREAD

**Issue by UrzaTRI** [rahtolsGitHub/Unofficial-30k-9th-edition#4]
1) The Legion Sicaran tank should have the option to add weapon sponsons (Heavy Bolters or Lascannons), but this option is missing.

2) If you select a Heavy Bolter for the pintle weapon upgrade, you get an error which says Battle Tank has too many selections of Heavy Bolter (maximum 1).

**Comment by rahtolsGitHub** [comment]
Solved. Thanks for bringing it up!
