### ISSUE TITLE
Legion Breacher Squad - Cannot add Special Weapons without adding extra Marines.

### ISSUE THREAD

**Issue by UrzaTRI** [rahtolsGitHub/Unofficial-30k-9th-edition#5]
The Legion Breacher Squad should be able to replace the Bolters of 2 x Marines with Special Weapons. However when I try to add 2 x Special Weapons Marines to the squad, I am unable to reduce the number of Bolter Marines in the squad below 9:
![image](https://user-images.githubusercontent.com/7566687/156920594-e7c35d79-f1aa-488e-8aff-32644c5258cd.jpeg)

Compared to the Legion Assault Squad, where I am able to do this:
![image](https://user-images.githubusercontent.com/7566687/156920607-fd0eee70-621e-41e1-8826-9807793f2581.jpeg)

Breacher Rules:
![image](https://user-images.githubusercontent.com/7566687/156920611-2bf421b2-764b-40a7-9d96-1d074b3e63f5.jpeg)

**Comment by rahtolsGitHub** [comment]
Thanks, fixed for march update.
